### ISSUE TITLE
"Are you sure?" dialogue when closing

### ISSUE THREAD

**Issue by AbsolutelyNoFires** [Aurora-Modders/AuroraPatch#17]
Closing the AuroraPatch form also closes Aurora. After a long playing session without saving, closing AuroraPatch and therefore Aurora will lose game progress. To prevent this, perhaps an "Are you sure?" "OK / Cancel" box when closing AuroraPatch.

**Comment by 01010100b** [comment]
Sure, feel free to create a PR.
